// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psvwuynqqbusdorcdhvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdnd1eW5xcWJ1c2RvcmNkaHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzcyNzcsImV4cCI6MjA3MzAxMzI3N30.rRKVWQsqHBt2Jp2xP2ROmFTvjHk91qdhJPj3ngJqIeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});